### ISSUE TITLE
IDs and Names of the states are hardcoded

### ISSUE THREAD

**Issue by pinkypeaky** [peterzernia/s2tp#12]
There is a list of states hardcoded at constants/index.js
Instead, it should be pulled dynamically from /api/v1/assignables/3376?include=[entitystate[nextstates]] where 3376 is ID of the entity you're like to move.

**Comment by peterzernia** [comment]
Awesome, thanks for the headsup. I didn't realize this endpoint existed or that the ids were different across processes. I just released v0.2.0 of the app onto the Google play store and it now uses this endpoint 😄.
